/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7^(th) triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
*/

/*Ans :76576500
Formula used:
no. of divisor of number n = Sum of (i+1) over all the prime factors of n 
where i = power of each prime factor 
example: 
24 = 2^3 X 3^1. 
so,
d(24) = (3 + 1).(1 + 1) = 4.2 = 8
hence there are 8 divisors. 
24 has divisors as 1,2,4,8,3,6,12,24.


*/


#include<iostream>

using namespace std;

int main(int argc,char** argv)
{
	long long n = 1;
	long long triNum = 1;
	int count = 0;
	const int divcount = 500;
	int psum;
	while(1)
	{
		triNum = (n*(n+1))/2;
		count = 1;
		long long primeFactor = 2;
		while(triNum > 1)
		{
			psum = 0;
			if(triNum % primeFactor == 0)
			{
				psum++;
				triNum = triNum / primeFactor;
				while(triNum % primeFactor == 0)
				{
					psum = psum + 1;
					triNum = triNum / primeFactor;	
				}
			}
			else
				primeFactor++;
			count = count*(psum + 1);
		}
		
		if(count > divcount )
			break;
		
		n++;
	}
	
	cout << n << " " << (n*(n+1))/2;
	return 0;
}
