/*
 *   Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *   By starting with 1 and 2, the first 10 terms will be:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *   Find the sum of all the even-valued terms in the sequence which do not exceed four million.
 *
 **/


#include <iostream>

using namespace std;

//recursive fibonacci generator
int fibonacci(int n)
{
    if(n<=1)
       return n;
    
    return fibonacci(n-1) + fibonacci(n-2);   
    
}    

int main(int argc, char** argv)
{
    int sum = 0;
    int i = 0;
    int j = 1;
    //use iterative fibonacci generator
    while(1) {

       i = i + j;
       if ( i >= 4000000)
          break;
       if( i % 2 == 0 )
          sum += i;   

       j = j + i ;
       if( j >= 4000000)
           break;
            
       if( j % 2 == 0 )
          sum += j;
    }

    cout << sum;
    return 0;   
}    
